# -------------------------------------------------------------------------------------
# Author Configuration | 作者配置
# -------------------------------------------------------------------------------------

name = "张大锅"
email = "1210500550@qq.com"
link = "https://zhang-weiming.github.io/"
avatar = "/img/programmer.png"
