# -------------------------------------------------------------------------------------
# Theme Core Configuration | 主题核心配置
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[search]
  enable = true
  type = "algolia"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false
  [search.algolia]
    index = "index.en"
    appID = "YKOM6PKLUY"
    searchKey = "a44c110d3ac360be2c69cd79d34b77a8"

[home]
  rss = 10
  [home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/img/programmer.png"
    avatarMenu = ""
    title = ""
    subtitle = "Daily problem record"
    typeit = true
    social = true
    disclaimer = ""
  [home.posts]
    enable = true
    paginate = 6

[social]
  GitHub = "zhang-weiming"
  Steam = "76561198331894362"
#  Zhihu = "xxxx"
#  Douban = "xxxx"
#  Devto = "xxxx"
  Bilibili = "88112403"
#  QQGroup = "awbwdTtSQ_-H5QGzeJxdWgv6JMbNehNM" # https://qun.qq.com/join.html
  Email = "1210500550@qq.com"
  RSS = true
#  Twitter = "xxxx"
#  Instagram = "xxxx"
#  Facebook = "xxxx"
#  Telegram = "xxxx"
#  Youtubelegacy = "xxxx"
  [social.Mastodon]
    id = "@xxxx"
    prefix = "https://mastodon.technology/"
