# -------------------------------------------------------------------------------------
# Theme Core Configuration | 主题核心配置
# See: https://fixit.lruihao.cn/zh-cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

description = "张大锅的博客"

#[search]
#  enable = true
#  type = "algolia"
#  contentLength = 4000
#  placeholder = ""
#  maxResultLength = 10
#  snippetLength = 50
#  highlightTag = "em"
#  absoluteURL = false
#  [search.algolia]
#    index = "index.zh-cn"
#    appID = "YKOM6PKLUY"
#    searchKey = "a44c110d3ac360be2c69cd79d34b77a8"

[home]
  rss = 10
  [home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/img/programmer.png"
    avatarMenu = ""
    title = ""
    subtitle = "日常问题记录"
    typeit = true
    social = true
    disclaimer = ""
  [home.posts]
    enable = true
    paginate = 6

[social]
  GitHub = "zhang-weiming"
  Steam = "76561198331894362"
#  Zhihu = "xxxx"
#  Douban = "xxxx"
#  Devto = "xxxx"
  Bilibili = "88112403"
#  QQGroup = "awbwdTtSQ_-H5QGzeJxdWgv6JMbNehNM" # https://qun.qq.com/join.html
  Email = "1210500550@qq.com"
  RSS = true

[pangu]
  enable = true
  selector = "article"

[watermark]
  enable = false
  content = '<img class="fixit-icon" src="/fixit.min.svg" alt="FixIt logo" /> FixIt 主题'
  opacity = 0.0125
  height = 21

[githubCorner]
  enable = true
  permalink = "https://github.com/zhang-weiming/zhang-weiming.github.io"
  title = "在 GitHub 上查看源代码"
  position = "right"

[gravatar]
  enable = true
  host = "gravatar.loli.net"
  style = "mp"
